import 'business.dart';

final List<Business> initialBusinesses = [
  Business(
    id: 1,
    name: "Limonata Standı",
    icon: "🍋",
    baseCost: 50,
    baseIncome: 0.5,
    description: "Basit bir limonata standı",
    requiredExperience: 1,
  ),
  Business(
    id: 2,
    name: "Gazete Dağıtımı",
    icon: "📰",
    baseCost: 100,
    baseIncome: 1.0,
    description: "Sabah gazetelerini dağıt",
    requiredExperience: 2,
  ),
  Business(
    id: 3,
    name: "Çiçek Dükkanı",
    icon: "🌸",
    baseCost: 250,
    baseIncome: 2.5,
    description: "Güzel çiçekler satıyorsunuz",
    requiredExperience: 3,
  ),
  Business(
    id: 4,
    name: "Dondurma Arabası",
    icon: "🍦",
    baseCost: 500,
    baseIncome: 5.0,
    description: "Seyyar dondurma satışı",
    requiredExperience: 4,
  ),
  Business(
    id: 5,
    name: "Kafe",
    icon: "☕",
    baseCost: 1000,
    baseIncome: 10.0,
    description: "Kahve ve tatlılar",
    requiredExperience: 5,
  ),
  Business(
    id: 6,
    name: "Fırın",
    icon: "🥖",
    baseCost: 2000,
    baseIncome: 20.0,
    description: "Taze ekmek ve börek",
    requiredExperience: 6,
  ),
  Business(
    id: 7,
    name: "Kitapevi",
    icon: "📚",
    baseCost: 3500,
    baseIncome: 35.0,
    description: "Bilgi ve edebiyat merkezi",
    requiredExperience: 7,
  ),
  Business(
    id: 8,
    name: "Berber Salonu",
    icon: "💈",
    baseCost: 5000,
    baseIncome: 50.0,
    description: "Saç kesimi ve tıraş",
    requiredExperience: 8,
  ),
  Business(
    id: 9,
    name: "Restoran",
    icon: "🍽️",
    baseCost: 10000,
    baseIncome: 100.0,
    description: "Lezzetli yemekler",
    requiredExperience: 9,
  ),
  Business(
    id: 10,
    name: "Spor Salonu",
    icon: "🏋️",
    baseCost: 15000,
    baseIncome: 150.0,
    description: "Fitness ve sağlık",
    requiredExperience: 10,
  ),
  Business(
    id: 11,
    name: "Sinema",
    icon: "🎬",
    baseCost: 25000,
    baseIncome: 250.0,
    description: "Film gösterimleri",
    requiredExperience: 11,
  ),
  Business(
    id: 12,
    name: "Süpermarket",
    icon: "🛒",
    baseCost: 35000,
    baseIncome: 350.0,
    description: "Her şey bir arada",
    requiredExperience: 12,
  ),
  Business(
    id: 13,
    name: "Otel",
    icon: "🏨",
    baseCost: 50000,
    baseIncome: 500.0,
    description: "Konforlu konaklama",
    requiredExperience: 13,
  ),
  Business(
    id: 14,
    name: "Alışveriş Merkezi",
    icon: "🏬",
    baseCost: 75000,
    baseIncome: 750.0,
    description: "Dev ticaret merkezi",
    requiredExperience: 14,
  ),
  Business(
    id: 15,
    name: "Hastane",
    icon: "🏥",
    baseCost: 100000,
    baseIncome: 1000.0,
    description: "Sağlık hizmetleri",
    requiredExperience: 15,
  ),
  Business(
    id: 16,
    name: "Banka",
    icon: "🏦",
    baseCost: 150000,
    baseIncome: 1500.0,
    description: "Finans merkezi",
    requiredExperience: 16,
  ),
  Business(
    id: 17,
    name: "Fabrika",
    icon: "🏭",
    baseCost: 250000,
    baseIncome: 2500.0,
    description: "Üretim tesisi",
    requiredExperience: 17,
  ),
  Business(
    id: 18,
    name: "Havalimanı",
    icon: "✈️",
    baseCost: 500000,
    baseIncome: 5000.0,
    description: "Uluslararası terminal",
    requiredExperience: 18,
  ),
  Business(
    id: 19,
    name: "Stadyum",
    icon: "🏟️",
    baseCost: 750000,
    baseIncome: 7500.0,
    description: "Dev spor kompleksi",
    requiredExperience: 19,
  ),
  Business(
    id: 20,
    name: "Kumarhane",
    icon: "🎰",
    baseCost: 1000000,
    baseIncome: 10000.0,
    description: "Eğlence merkezi",
    requiredExperience: 20,
  ),
  Business(
    id: 21,
    name: "Teknoloji Kampüsü",
    icon: "💻",
    baseCost: 2000000,
    baseIncome: 20000.0,
    description: "İnovasyon merkezi",
    requiredExperience: 21,
  ),
  Business(
    id: 22,
    name: "Uzay Üssü",
    icon: "🚀",
    baseCost: 5000000,
    baseIncome: 50000.0,
    description: "Uzay araştırma merkezi",
    requiredExperience: 22,
  ),
];